Get-AppxPackage *Microsoft.BingFoodAndDrink* | Remove-AppxPackage
Get-AppxPackage *Microsoft.BingTravel* | Remove-AppxPackage
Get-AppxPackage *Microsoft.BingFinance* | Remove-AppxPackage
Get-AppxPackage *Microsoft.BingSports* | Remove-AppxPackage
Get-AppxPackage *Microsoft.BingHealthAndFitness* | Remove-AppxPackage
Get-AppxPackage *Microsoft.ZuneVideo* | Remove-AppxPackage
Get-AppxPackage *Microsoft.ZuneMusic* | Remove-AppxPackage
get-appxpackage *Microsoft.WindowsFeedbackHub | Remove-AppxPackage
get-appxpackage *Microsoft.Wallet* | Remove-AppxPackage
get-appxpackage *Microsoft.WindowsAlarms* | Remove-AppxPackage
get-appxpackage *Microsoft.WindowsCalculator* | Remove-AppxPackage
get-appxpackage *Microsoft.WindowsReadingList* | Remove-AppxPackage
get-appxpackage *Microsoft.3DBuilder* | Remove-AppxPackage
get-appxpackage *Microsoft.People* | Remove-AppxPackage
get-appxpackage *Microsoft.MicrosoftStickyNotes* | Remove-AppxPackage